---
output: github_document
---

<!---
permalink: /teaching/dojo_intro
title: IDDO Data Dojo 1 - Hey presto dojo repo intro
categories:
  - howto
tags:
  - ReproducibleResearch
toc: true
author_profile: false
--->

*This tutorial is for the first session of the IDDO Data Dojo, a recurring workshop to discuss research/data skills and shortcuts. In this tutorial, we initialise a GitHub repository for the data dojo and get everyone set up.*

Before we start, we need everyone to:

- Have `Git` installed. (`Git` comes with macs/linux, but Windows users will need to download). To check `Git` is installed, in your terminal, type: `git version`
- Have a GitHub profile set up.
- Have their GitHub profile included in the IDDO GitHub organisation.
- Ideally, have followed a beginner tutorial to git/GitHub - see [Resources](/teaching/dojo_intro#resources) below.

## Structure

Welcome to the IDDO Data Dojo! We'll use this session to share interesting tips and tricks for data processing, coding, and reproducible research.

To get started, we will need to set up a GitHub repo to share resources for future workshops - the task for today! We will cover:

- How to initialise a git repo locally, and on GitHub
- How to structure a git repo, including:
  - directory structure
  - README
  - .gitignore
- How to add content to our repo - we'll add our very first post in markdown.
- How to use somebody else's git repo, including forking, cloning, and pull requests

## Resources

- Have a look at my [beginner tutorial](https://lu-harr.github.io/teaching/version_control) for git and GitHub
- Our Coding Club's intro to GitHub [tutorial](https://ourcodingclub.github.io/tutorials/git/)
- Our Coding Club's [tutorial](https://ourcodingclub.github.io/tutorials/git-for-labs/) for setting up a lab repo 
- [Git is my lab book](https://git-is-my-lab-book.net) A compendium of guides/tutorials (see their GitHub here: https://github.com/robmoss/git-is-my-lab-book/)

[Off we go to GitHub!]

## Terminology

A quick recap! By the end of today, we should be familiar with:

- Staging/committing/pushing
- Cloning/forking/pulling/pull requests



